export const CHAINLINK_TOKEN_DECIMALS = 18;

export const AMOUNT_TO_FUND_VRF_COORDINATOR = BigInt(
  1.6 * 10 ** CHAINLINK_TOKEN_DECIMALS
);
export const AMOUNT_TO_FUND_AUTOMATION = BigInt(
  0.29 * 10 ** CHAINLINK_TOKEN_DECIMALS
);
