import { classroomFactoryContracts } from "@/contracts/contracts";
import Link from "next/link";
import { appNetworkPathRecord, appNetworkRecord } from "@/contracts/settings";

export default async function Page() {
  return (
    <div className="p-4 space-y-4">
      <div className="font-bold">Classroom Factory Contract</div>
      <div>
        <div className="font-bold">Key features:</div>
        <ul className="list-disc list-inside">
          <li>
            Classroom contract is generated by ClassroomFactory contract by
            factory pattern
          </li>
          <li>Use of libraries,structs and enums in solidity</li>
          <li>
            Deploying of contracts for different networks is performed by
            hardhat ignition
          </li>
          <li>Solidity best practices</li>
          <li>All the smart contracts are tested in hardhat</li>
          <li>
            NebulaApi (on-chain ai agent) is used to interact with smart
            contracts
          </li>
        </ul>
      </div>
      <div>
        <div className="mb-2">Select your network:</div>
        <div className="space-x-4">
          {classroomFactoryContracts.map((_) => (
            <div key={_.address} className="border rounded-md p-1 inline-block">
              <Link
                href={`classroom/networks/${appNetworkPathRecord[_.chainId]}`}
              >
                {appNetworkRecord[_.chainId]?.name}
              </Link>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
